aa: rand-m9-mstd0.5-inc1
amp: true
apex_amp: true
aq_asym: false
aq_bitw: null
aq_enable: false
aq_mode: lsq
aq_neg: null
aq_pos: null
as_enable: false
as_mode: Identity
as_patterns: '1:1'
aug_splits: 0
batch_size: 512
bn_eps: null
bn_momentum: null
bn_tf: false
channels_last: false
checkpoint_hist: 3
clip_grad: null
clip_mode: norm
color_jitter: 0.4
cooldown_epochs: 10
crop_pct: 0.9
cutmix: 0
cutmix_minmax: null
data_dir: /opt/dataset/imagenet
dataset: imagenet
decay_epochs: 30
decay_rate: 0.1
dist_bn: ''
distributed: true
down_block_type: default
drop: 0.0
drop_block: null
drop_connect: null
drop_path: null
epoch_repeats: 0.0
epochs: 200
eval_metric: top1
experiment: ''
gp: null
hflip: 0.5
img_size: 224
# initial_checkpoint: /home/xts/code/njeans/MySparsity/Ternary-ViT/output/train/20240112-111709-imagenet_mobilenetv2-224/mobilenetv2_1.0_fp32.pth
input_size: null
interpolation: bicubic
jsd: false
kd_alpha: 1.0
kd_type: last
local_rank: 0
log_interval: 50
log_wandb: false
lr: 0.015
lr_cycle_limit: 1
lr_cycle_mul: 1.0
lr_noise: null
lr_noise_pct: 0.67
lr_noise_std: 1.0
mean:
- 0.485
- 0.456
- 0.406
min_lr: 1.0e-05
mixup: 0
mixup_mode: batch
mixup_off_epoch: 0
mixup_prob: 1.0
mixup_switch_prob: 0.5
model: imagenet_cir_mobilenetv2
model_ema: false
model_ema_decay: 0.9998
model_ema_force_cpu: false
momentum: 0.9
native_amp: false
no_aug: false
no_bn: false
no_prefetcher: true
no_resume_opt: false
num_classes: 1000
opt: sgd
opt_betas: null
opt_eps: null
output: ''
patience_epochs: 10
pin_mem: false
post_res_bn: false
pretrained: false
qmodules: []
quant_teacher: false
ratio:
- 0.75
- 1.3333333333333333
recount: 1
recovery_interval: 0
remode: pixel
replace_ln_by_bn: false
replace_relu: false
reprob: 0.25
resplit: false
resq_asym: false
resq_bitw: null
resq_enable: false
resq_mode: lsq
resq_modules: []
resq_neg: null
resq_pos: null
resume: ''
save_images: false
scale:
- 0.08
- 1.0
sched: cosine
seed: 3407
smoothing: 0.1
split_bn: false
start_epoch: null
std:
- 0.229
- 0.224
- 0.225
sync_bn: true
# teacher: imagenet_mobilenetv2
# teacher_checkpoint: /home/xts/code/njeans/MySparsity/Ternary-ViT/output/train/20240112-111709-imagenet_mobilenetv2-224/mobilenetv2-c5e733a8.pth
torchscript: false
train_interpolation: random
train_split: train
tta: 0
use_bn: true
use_distill_head: false
use_dual_skip: false
use_kd: false
use_layer_scale: false
use_multi_epochs_loader: false
use_relu: false
use_skip: false
use_token_kd: false
val_split: validation
validation_batch_size_multiplier: 1
vflip: 0.0
warmup_epochs: 5
warmup_lr: 1e-6
weight_decay: 0.00004
workers: 4
pretrain: True
finetune: False
log_name: pretrain_imagenet_A6000X4_2
resume: /home/xts/code/njeans/MySparsity/Ternary-ViT/output/train/20240225-211247-pretrain_imagenet_cir_nas_mobilenetv2-224/model_best.pth.tar
# resume: "/home/xts/code/njeans/MySparsity/Ternary-ViT/output/train/20240122-144235-imagenet_cir_mobilenetv2-224/checkpoint-11.pth.tar"